### PR TITLE
New website

### PR DESCRIPTION
**Pull request by ghost**
New changes need to be checked a bit : 
like : is this really usefull ?
<? <?php echo '<?xml version="1.0" encoding="UTF-8" ?>' ?>

Background need to be changed or something ! need you're advice.

The picture magnify system should not need any changes !

Tell me you're opinion !

### CODE REVIEW

**Comment by abma** [comment]
```
 like : is this really usefull ?
 <? <?php echo '<?xml version="1.0" encoding="UTF-8" ?>' ?>
```

where do you see this code?

i only see 

```
 <?php echo '<?xml version="1.0" encoding="UTF-8" ?>' ?>
```

and this code is "useful" as <? is a shortcut for <?php

**Comment by ghost** [comment]
This line is just before the html code in the index.php files and i just don't know what it make ... si i removed it so if its necessairy to keep it i add it in new file.

**Comment by abma** [comment]
it adds <?xml version="1.0" encoding="UTF-8" ?> to the header...

**Comment by abma** [comment]
thanks a lot!

**Comment by renefritze** [comment]
Shiny! :+1:

**Pull request merged**
