### PR TITLE
Validator test done !

### PR DESCRIPTION
**Pull request by ghost**
The only errors are comming from the php code ! not the html code !

mabe 1 thing isn't great its the using or rel="gallery1"
but that the only way to make slider work because i don't want to touch any of the java scripts !

### CODE REVIEW

**Comment by abma** [comment]
hmm, this doesn't look like validation is fixed as nothing was changed?!

https://github.com/springlobby/springlobby-website/pull/2/files

**Comment by ghost** [comment]
Yeah but all those erros are made by the php code ! can't fix php code he is good ...

**Comment by abma** [comment]
great, thanks!

**Comment by ghost** [comment]
Your welcome

**Pull request merged**
